name: "Publish alpine-sshd Docker Image"

on:
  release:
    types: [published]
    
jobs:
  build-docker-image:
    runs-on: "ubuntu-latest"

    steps:
      - name: Preview Postfix
        if: github.event == 'push'
        run: |
          SUB="tag"
          if [[ "${github.ref}" == *"${SUB}"* ]]; then \
            REPLACE= \
            REF="${github.ref}" \
            POSTFIX=echo "${REF//(refs\/tags\/(v([\d]*){1}.([\d]*){1}(.?)([\d]+)?))/REPLACE}" \
          fi \
          echo '::set-output name=TAG_POSTFIX::POSTFIX'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
            "ghcr.io/${{ github.repository }}"
          tags: type=semver,pattern={{version}}

      - name: Build & Push Dev Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: final
          cache-to: "type=local,dest=$(PWD)/cache"
          labels: |
            "com.keplerdev.alpine-sshd.maintainer: Jesse Nicholson <jesse@keplerdev.com>"
            "com.keplerdev.alpine-sshd.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-sshd.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-sshd.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          build-args: |
            BASE_IMAGE=jessenich91/alpine-zsh
            BASE_IMAGE_TAG=latest
            SSH_USER=jessenich
            SSH_USER_SHELL="/bin/zsh"
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}


      - name: Build & Push Dev Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: artifact
          cache-from: "type=local,src=$(PWD)/cache"
          labels: |
            "com.keplerdev.alpine-sshd.maintainer: Jesse Nicholson <jesse@keplerdev.com>"
            "com.keplerdev.alpine-sshd.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-sshd.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-sshd.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          build-args: |
            ${{ env.COMMON_ARGS }}
            BASE_IMAGE_TAG=latest
            SSH_USER=jessenich
            SSH_USER_SHELL="/bin/zsh"
          outputs: "type=local,dest=$(PWD)/out/"
          pull: true
          push: false

      - run: ls /var/cache/docker/docker-alpine-sshd_artifact
