name: "Publish alpine-sshd Docker Image"

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build-docker-image:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Dev Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: final
          labels: |
            "com.keplerdev.alpine-sshd.maintainer: Jesse Nicholson <jesse@keplerdev.com>"
            "com.keplerdev.alpine-sshd.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-sshd.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-sshd.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            BASE_IMAGE=jessenich91/alpine-zsh
            BASE_IMAGE_TAG=glibc-latest
            SSH_USER=jessenich
            SSH_USER_SHELL="/bin/zsh"
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:glibc-${{ steps.semver.outputs.non-prefixed }}


      - name: Build & Push Dev Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: final
          labels: |
            "com.keplerdev.alpine-sshd.maintainer: Jesse Nicholson <jesse@keplerdev.com>"
            "com.keplerdev.alpine-sshd.source-sha": ${{ github.sha }}
            "com.keplerdev.alpine-sshd.repository.github.url: https://github.com/${{ github.repository }}"
            "com.keplerdev.alpine-sshd.repository.dockerhub.url: https://dockerhub.com/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}"
          build-args: |
            BASE_IMAGE=jessenich91/alpine-zsh
            BASE_IMAGE_TAG=latest
            SSH_USER=jessenich
            SSH_USER_SHELL="/bin/zsh"
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.semver.outputs.non-prefixed }}